[project]
name = "monopoly-telemetry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kushagra Bharti", email = "kushagrabharti@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "orjson>=3.11.5",
    "pydantic>=2.12.5",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
lint = [
    "ruff>=0.14.10",
]
test = [
    "pytest>=9.0.2",
]
type = [
    "mypy>=1.19.1",
]
