[project]
name = "monopoly-arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kushagra Bharti", email = "kushagrabharti@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "jsonschema>=4.25.1",
    "monopoly-engine",
    "monopoly-telemetry",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
monopoly-engine = { workspace = true, editable = true }
monopoly-telemetry = { workspace = true, editable = true }

[dependency-groups]
lint = [
    "ruff>=0.14.10",
]
test = [
    "pytest>=9.0.2",
]
type = [
    "mypy>=1.19.1",
]
